imximage: fix compiling issue caused by autoconf.h
commit e97bdfa5da70600e9755d6f70713744ed25f62c3 ("tools/imximage: share DCD information via Kconfig")
includes autoconf.h in imximage.c. But generated/autoconf.h is included from include/linux/kconfig.h.

Fixes:

tools/imximage.c:14:10: fatal error: generated/autoconf.h: No such file or directory
   14 | #include <generated/autoconf.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

Signed-off-by: Pierre-Jean Texier <pjtexier@koncepto.io>