compiler.h: fix musl build
Since commit 664689f ("env: add missing <compiler.h> header file"), the
header <compiler.h> is used to find correct declarations.

But in case of a musl build, it is mandatory to include <sys/types.h> for
ulong.

Fixes:

include/env.h:159:1: error: unknown type name ‘ulong’; did you mean ‘long’?

Signed-off-by: Pierre-Jean Texier <pjtexier@koncepto.io>